html_content = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Four Webviews</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            height: 98vh;
            display: grid;
            grid-template-columns: 50% 50%; /* 分成两列 */
            grid-template-rows: 50% 50%;    /* 分成两行 */
        }
        
        iframe {
            border: none;
            width: 100%;
            height: 100%;
        }
        
        #top-left {
            grid-column: 1 / 2;
            grid-row: 1 / 2;
        }
        
        #top-right {
            grid-column: 2 / 3;
            grid-row: 1 / 2;
        }
        
        #bottom-left {
            grid-column: 1 / 2;
            grid-row: 2 / 3;
        }
        
        #bottom-right {
            grid-column: 2 / 3;
            grid-row: 2 / 3;
        }
    </style>
</head>
<body>
    <div id="top-left">
        <iframe src="http://pms.pro.js.sgcc.com.cn:32100/yj-pms-coordinate-editing/#/equipManage?cHNySWQ9MTQwMDA4NzIwMTQ2MjQmaXNKbHhBZGRyZXNzPXRydWUmcHNyVHlwZT0wMiZleFZhbHVlPTAxMTAmbGluZUlkPXp6YnlxVHJlZUdyb3VwQDEwREtYLTYzNzc0NSZsaW5lVHlwZT1keXRxJnNibWM9JUU1JUFFJTg5JUU1JUIzJUIwMDY5IyVFNSU4OSU4RCVFNiU5NCVCRSVFNCVCOCVBRCVFNSU4RiVCMCVFNSU4NSVBQyVFNSU4RiU5OCZwc3JJZHM9MmNhZDFkYWQ3YWZmODA4MDgxNmVlZjQ1NjAwMTZmMmNhYmQ0MmYzNjM3LDI2ZjUyZmVhNzI4YTA2ZGVlYzYwZTQ0MjYzMDE2MTI2ZjNkOTA5M2U4NiwxNDAwMDE5OTkyMzk5NCwxNDAwMDE5OTIwMTQwMSwxNDAwMDQ5NjczOTcxMyw2Njk4OTNmNGJhOGEwNmRlZWY1YzQ2YjRlMzAxNWM2Njk3ZjYxZjc2NGMsMTQwMDAxOTkyMDExMjQsMzVkMmUzMTA2NGZmODA4MDgxNmVlZjQ1NjAwMTZmMzVkMTc0MWM3M2NjLDEwMDAwMDAwMDQ3MzcwLDdkODkxNDYyMDg4YTA2ZGVlZDYwNTYxMDM1MDE2MDdkODdiNjY4MjhmOCwxNDAwMDY0MDEyNjgwMCwxNDAwMDQ5NjY5OTc4NSwxNDAwMDQ5NjcxMzkwNiwxMDAwMDAwMDA0Njk1MywxNDAwMDA4NDg5ODczNywxNDAwMTExNzMxNDc0NywxNDAwMDQ5NjczMDI1NixiMzI1NWUwZDA1ZmY4MDgwODE2ZjkyM2YxMDAxNzBiMzIzM2EwYjY0NmMsMTQwMDA0OTk2NjAxMTUsMTQwMDEwMDU4NDE2ODMsYjMxZWUwMjJjZGZmODA4MDgxNmY5MjNmMTAwMTcwYjMxY2JjMzg2NDRhLDEwMDAwMDAwMDQyODcxLDE0MDAwNDI0MDk5MTcyLDE0MDAwODcwNjA2NjM4LGJiNDJlMzE0YTQ4YTA2ZGVlYzY3NjdiZWM4MDE2N2JiNDA4OWVjNTE1NSwyY2IxNjFiNmI5ZmY4MDgwODE2ZWVmNDU2MDAxNmYyY2IwMTgyNjM2NTEsMTQwMDAwODcwNjM1OTEsMTQwMDAwODcwNjQzMTAsMTQwMDAwODcwNjU5NTQsMTQwMDAwODcwNjY0MjAsMTQwMDAwODcwNjY2MDIsMTQwMDAwODcwNjYyNjUsMTQwMDAwODcwNjU1MTcsMTQwMDAyNDQ2MjE2MDMsMTQwMDA2MzU3MDUzNjksMTQwMDA0MjQwODkzMTYsMTQwMDA0MjQwNTc5OTQsMTQwMDEwMDU4NDkzMjIsYjEzYWYwOTc4ZWZmODA4MDgxNmU5NGRjOTQwMTZlYjEzN2VjYTg1MDcwLDE0MDAxMDkyMjM4ODQ3LDE0MDAxMTY2Mjg0MTI5LDE0MDAxMTY2Mjg2MDk5LDE0MDAxMTY2MjkxNzU5LDE0MDAxMTY2MzEwODg5LDE0MDAxMTcyNzQwMzk4LDIwMDcxNDNjMjJmZjgwODA4MTU2MTYzYWIyMDE1NjIwMDcwMjRlMWUzNyxkNzY5NmU1MWUwZmY4MDgwODE1NGJlY2UzOTAxNTRkNzY4ZjZlYzI1ODAsZDc3NTFiYzNmYWZmODA4MDgxNTRiZWJmYmMwMTU0ZDc3NGVhNTY0NWRhLGQ3MWY3OGI2NGE4YTA2ZGVlYzU0YmVjYjU1MDE1NGQ3MWY0ODZlM2I2OCxkNzlhYjFjODJmZmY4MDgwODE1NGJlYmZiYzAxNTRkNzlhODAyNjQ2MTQsNmNkZmFiNzIzYThhMDZkZWVkNTg0OTY5NDQwMTU4NmNkZjE4MDg2YTBkLDZjYzZjZmRmMmM4YTA2ZGVlZDU4NDk2OTQ0MDE1ODZjYzYzY2YzNjkzNCwxMDAwMDAwMDQ4Njc2MywxYzQ5MjE0YmU0ZmY4MDgwODE2MTEyNmY4NjAxNjExYzQ5MGYxNzFlODAsMTdhOTk1MTIwOWZmODA4MDgxNjNkMTA2NDcwMTY0MTdhODA3YzE1ODBhLGNlMzIzODc4LTFhYWEtNGE2YS1hMDRkLTgzZDBjNzRkODlhZSxiYjM5MmIzNjA2OGEwNmRlZWM2NzY3YmVjODAxNjdiYjM2ZDI2ODUwZDQsOGE4ZTUzOTkzYmZmODA4MDgxNmM1MzNhOTAwMTZjOGE4Y2IzMzU3NWY4LDM3YTVjNTdkMWRmZjgwODA4MTZlZWY0NjVlMDE2ZjM3YTMyMWNkNjAyYyw5NWZjMWUyMi1kZDc4LTQwYzMtYWNlNy03NGNjYzVmNjBjODcsZDlkMzYyYjYtZDBhMC00ZTI0LThmODAtYWEwODc3MWZjYzE0LGMyNGU3OGE0LTE3ZDItNDBlYy1hZmE3LWFjYjAxYzRlMzU2NyxiZDcwYzUyMy1kZTIxLTQ4YjktYjJhNS01N2NkZTNjY2MyM2YsMTQwMDEwMDU4NDYzOTg=" title="Top Left"></iframe>
    </div>
    <div id="top-right">
        <iframe src="http://pms.pro.js.sgcc.com.cn:32100/yj-pms-coordinate-editing/#/equipManage?cHNySWQ9MTQwMDA4NzIwMTQ2MjQmaXNKbHhBZGRyZXNzPXRydWUmcHNyVHlwZT0wMiZleFZhbHVlPTAxMTAmbGluZUlkPXp6YnlxVHJlZUdyb3VwQDEwREtYLTYzNzc0NSZsaW5lVHlwZT1keXRxJnNibWM9JUU1JUFFJTg5JUU1JUIzJUIwMDY5IyVFNSU4OSU4RCVFNiU5NCVCRSVFNCVCOCVBRCVFNSU4RiVCMCVFNSU4NSVBQyVFNSU4RiU5OCZwc3JJZHM9MmNhZDFkYWQ3YWZmODA4MDgxNmVlZjQ1NjAwMTZmMmNhYmQ0MmYzNjM3LDI2ZjUyZmVhNzI4YTA2ZGVlYzYwZTQ0MjYzMDE2MTI2ZjNkOTA5M2U4NiwxNDAwMDE5OTkyMzk5NCwxNDAwMDE5OTIwMTQwMSwxNDAwMDQ5NjczOTcxMyw2Njk4OTNmNGJhOGEwNmRlZWY1YzQ2YjRlMzAxNWM2Njk3ZjYxZjc2NGMsMTQwMDAxOTkyMDExMjQsMzVkMmUzMTA2NGZmODA4MDgxNmVlZjQ1NjAwMTZmMzVkMTc0MWM3M2NjLDEwMDAwMDAwMDQ3MzcwLDdkODkxNDYyMDg4YTA2ZGVlZDYwNTYxMDM1MDE2MDdkODdiNjY4MjhmOCwxNDAwMDY0MDEyNjgwMCwxNDAwMDQ5NjY5OTc4NSwxNDAwMDQ5NjcxMzkwNiwxMDAwMDAwMDA0Njk1MywxNDAwMDA4NDg5ODczNywxNDAwMTExNzMxNDc0NywxNDAwMDQ5NjczMDI1NixiMzI1NWUwZDA1ZmY4MDgwODE2ZjkyM2YxMDAxNzBiMzIzM2EwYjY0NmMsMTQwMDA0OTk2NjAxMTUsMTQwMDEwMDU4NDE2ODMsYjMxZWUwMjJjZGZmODA4MDgxNmY5MjNmMTAwMTcwYjMxY2JjMzg2NDRhLDEwMDAwMDAwMDQyODcxLDE0MDAwNDI0MDk5MTcyLDE0MDAwODcwNjA2NjM4LGJiNDJlMzE0YTQ4YTA2ZGVlYzY3NjdiZWM4MDE2N2JiNDA4OWVjNTE1NSwyY2IxNjFiNmI5ZmY4MDgwODE2ZWVmNDU2MDAxNmYyY2IwMTgyNjM2NTEsMTQwMDAwODcwNjM1OTEsMTQwMDAwODcwNjQzMTAsMTQwMDAwODcwNjU5NTQsMTQwMDAwODcwNjY0MjAsMTQwMDAwODcwNjY2MDIsMTQwMDAwODcwNjYyNjUsMTQwMDAwODcwNjU1MTcsMTQwMDAyNDQ2MjE2MDMsMTQwMDA2MzU3MDUzNjksMTQwMDA0MjQwODkzMTYsMTQwMDA0MjQwNTc5OTQsMTQwMDEwMDU4NDkzMjIsYjEzYWYwOTc4ZWZmODA4MDgxNmU5NGRjOTQwMTZlYjEzN2VjYTg1MDcwLDE0MDAxMDkyMjM4ODQ3LDE0MDAxMTY2Mjg0MTI5LDE0MDAxMTY2Mjg2MDk5LDE0MDAxMTY2MjkxNzU5LDE0MDAxMTY2MzEwODg5LDE0MDAxMTcyNzQwMzk4LDIwMDcxNDNjMjJmZjgwODA4MTU2MTYzYWIyMDE1NjIwMDcwMjRlMWUzNyxkNzY5NmU1MWUwZmY4MDgwODE1NGJlY2UzOTAxNTRkNzY4ZjZlYzI1ODAsZDc3NTFiYzNmYWZmODA4MDgxNTRiZWJmYmMwMTU0ZDc3NGVhNTY0NWRhLGQ3MWY3OGI2NGE4YTA2ZGVlYzU0YmVjYjU1MDE1NGQ3MWY0ODZlM2I2OCxkNzlhYjFjODJmZmY4MDgwODE1NGJlYmZiYzAxNTRkNzlhODAyNjQ2MTQsNmNkZmFiNzIzYThhMDZkZWVkNTg0OTY5NDQwMTU4NmNkZjE4MDg2YTBkLDZjYzZjZmRmMmM4YTA2ZGVlZDU4NDk2OTQ0MDE1ODZjYzYzY2YzNjkzNCwxMDAwMDAwMDQ4Njc2MywxYzQ5MjE0YmU0ZmY4MDgwODE2MTEyNmY4NjAxNjExYzQ5MGYxNzFlODAsMTdhOTk1MTIwOWZmODA4MDgxNjNkMTA2NDcwMTY0MTdhODA3YzE1ODBhLGNlMzIzODc4LTFhYWEtNGE2YS1hMDRkLTgzZDBjNzRkODlhZSxiYjM5MmIzNjA2OGEwNmRlZWM2NzY3YmVjODAxNjdiYjM2ZDI2ODUwZDQsOGE4ZTUzOTkzYmZmODA4MDgxNmM1MzNhOTAwMTZjOGE4Y2IzMzU3NWY4LDM3YTVjNTdkMWRmZjgwODA4MTZlZWY0NjVlMDE2ZjM3YTMyMWNkNjAyYyw5NWZjMWUyMi1kZDc4LTQwYzMtYWNlNy03NGNjYzVmNjBjODcsZDlkMzYyYjYtZDBhMC00ZTI0LThmODAtYWEwODc3MWZjYzE0LGMyNGU3OGE0LTE3ZDItNDBlYy1hZmE3LWFjYjAxYzRlMzU2NyxiZDcwYzUyMy1kZTIxLTQ4YjktYjJhNS01N2NkZTNjY2MyM2YsMTQwMDEwMDU4NDYzOTg=" title="Top Right"></iframe>
    </div>
    <div id="bottom-left">
        <iframe src="http://pms.pro.js.sgcc.com.cn:32100/yj-pms-coordinate-editing/#/equipManage?cHNySWQ9MTQwMDA4NzIwMTQ2MjQmaXNKbHhBZGRyZXNzPXRydWUmcHNyVHlwZT0wMiZleFZhbHVlPTAxMTAmbGluZUlkPXp6YnlxVHJlZUdyb3VwQDEwREtYLTYzNzc0NSZsaW5lVHlwZT1keXRxJnNibWM9JUU1JUFFJTg5JUU1JUIzJUIwMDY5IyVFNSU4OSU4RCVFNiU5NCVCRSVFNCVCOCVBRCVFNSU4RiVCMCVFNSU4NSVBQyVFNSU4RiU5OCZwc3JJZHM9MmNhZDFkYWQ3YWZmODA4MDgxNmVlZjQ1NjAwMTZmMmNhYmQ0MmYzNjM3LDI2ZjUyZmVhNzI4YTA2ZGVlYzYwZTQ0MjYzMDE2MTI2ZjNkOTA5M2U4NiwxNDAwMDE5OTkyMzk5NCwxNDAwMDE5OTIwMTQwMSwxNDAwMDQ5NjczOTcxMyw2Njk4OTNmNGJhOGEwNmRlZWY1YzQ2YjRlMzAxNWM2Njk3ZjYxZjc2NGMsMTQwMDAxOTkyMDExMjQsMzVkMmUzMTA2NGZmODA4MDgxNmVlZjQ1NjAwMTZmMzVkMTc0MWM3M2NjLDEwMDAwMDAwMDQ3MzcwLDdkODkxNDYyMDg4YTA2ZGVlZDYwNTYxMDM1MDE2MDdkODdiNjY4MjhmOCwxNDAwMDY0MDEyNjgwMCwxNDAwMDQ5NjY5OTc4NSwxNDAwMDQ5NjcxMzkwNiwxMDAwMDAwMDA0Njk1MywxNDAwMDA4NDg5ODczNywxNDAwMTExNzMxNDc0NywxNDAwMDQ5NjczMDI1NixiMzI1NWUwZDA1ZmY4MDgwODE2ZjkyM2YxMDAxNzBiMzIzM2EwYjY0NmMsMTQwMDA0OTk2NjAxMTUsMTQwMDEwMDU4NDE2ODMsYjMxZWUwMjJjZGZmODA4MDgxNmY5MjNmMTAwMTcwYjMxY2JjMzg2NDRhLDEwMDAwMDAwMDQyODcxLDE0MDAwNDI0MDk5MTcyLDE0MDAwODcwNjA2NjM4LGJiNDJlMzE0YTQ4YTA2ZGVlYzY3NjdiZWM4MDE2N2JiNDA4OWVjNTE1NSwyY2IxNjFiNmI5ZmY4MDgwODE2ZWVmNDU2MDAxNmYyY2IwMTgyNjM2NTEsMTQwMDAwODcwNjM1OTEsMTQwMDAwODcwNjQzMTAsMTQwMDAwODcwNjU5NTQsMTQwMDAwODcwNjY0MjAsMTQwMDAwODcwNjY2MDIsMTQwMDAwODcwNjYyNjUsMTQwMDAwODcwNjU1MTcsMTQwMDAyNDQ2MjE2MDMsMTQwMDA2MzU3MDUzNjksMTQwMDA0MjQwODkzMTYsMTQwMDA0MjQwNTc5OTQsMTQwMDEwMDU4NDkzMjIsYjEzYWYwOTc4ZWZmODA4MDgxNmU5NGRjOTQwMTZlYjEzN2VjYTg1MDcwLDE0MDAxMDkyMjM4ODQ3LDE0MDAxMTY2Mjg0MTI5LDE0MDAxMTY2Mjg2MDk5LDE0MDAxMTY2MjkxNzU5LDE0MDAxMTY2MzEwODg5LDE0MDAxMTcyNzQwMzk4LDIwMDcxNDNjMjJmZjgwODA4MTU2MTYzYWIyMDE1NjIwMDcwMjRlMWUzNyxkNzY5NmU1MWUwZmY4MDgwODE1NGJlY2UzOTAxNTRkNzY4ZjZlYzI1ODAsZDc3NTFiYzNmYWZmODA4MDgxNTRiZWJmYmMwMTU0ZDc3NGVhNTY0NWRhLGQ3MWY3OGI2NGE4YTA2ZGVlYzU0YmVjYjU1MDE1NGQ3MWY0ODZlM2I2OCxkNzlhYjFjODJmZmY4MDgwODE1NGJlYmZiYzAxNTRkNzlhODAyNjQ2MTQsNmNkZmFiNzIzYThhMDZkZWVkNTg0OTY5NDQwMTU4NmNkZjE4MDg2YTBkLDZjYzZjZmRmMmM4YTA2ZGVlZDU4NDk2OTQ0MDE1ODZjYzYzY2YzNjkzNCwxMDAwMDAwMDQ4Njc2MywxYzQ5MjE0YmU0ZmY4MDgwODE2MTEyNmY4NjAxNjExYzQ5MGYxNzFlODAsMTdhOTk1MTIwOWZmODA4MDgxNjNkMTA2NDcwMTY0MTdhODA3YzE1ODBhLGNlMzIzODc4LTFhYWEtNGE2YS1hMDRkLTgzZDBjNzRkODlhZSxiYjM5MmIzNjA2OGEwNmRlZWM2NzY3YmVjODAxNjdiYjM2ZDI2ODUwZDQsOGE4ZTUzOTkzYmZmODA4MDgxNmM1MzNhOTAwMTZjOGE4Y2IzMzU3NWY4LDM3YTVjNTdkMWRmZjgwODA4MTZlZWY0NjVlMDE2ZjM3YTMyMWNkNjAyYyw5NWZjMWUyMi1kZDc4LTQwYzMtYWNlNy03NGNjYzVmNjBjODcsZDlkMzYyYjYtZDBhMC00ZTI0LThmODAtYWEwODc3MWZjYzE0LGMyNGU3OGE0LTE3ZDItNDBlYy1hZmE3LWFjYjAxYzRlMzU2NyxiZDcwYzUyMy1kZTIxLTQ4YjktYjJhNS01N2NkZTNjY2MyM2YsMTQwMDEwMDU4NDYzOTg=" title="Bottom Left"></iframe>
    </div>
    <div id="bottom-right">
        <iframe src="http://pms.pro.js.sgcc.com.cn:32100/yj-pms-coordinate-editing/#/equipManage?cHNySWQ9MTQwMDA4NzIwMTQ2MjQmaXNKbHhBZGRyZXNzPXRydWUmcHNyVHlwZT0wMiZleFZhbHVlPTAxMTAmbGluZUlkPXp6YnlxVHJlZUdyb3VwQDEwREtYLTYzNzc0NSZsaW5lVHlwZT1keXRxJnNibWM9JUU1JUFFJTg5JUU1JUIzJUIwMDY5IyVFNSU4OSU4RCVFNiU5NCVCRSVFNCVCOCVBRCVFNSU4RiVCMCVFNSU4NSVBQyVFNSU4RiU5OCZwc3JJZHM9MmNhZDFkYWQ3YWZmODA4MDgxNmVlZjQ1NjAwMTZmMmNhYmQ0MmYzNjM3LDI2ZjUyZmVhNzI4YTA2ZGVlYzYwZTQ0MjYzMDE2MTI2ZjNkOTA5M2U4NiwxNDAwMDE5OTkyMzk5NCwxNDAwMDE5OTIwMTQwMSwxNDAwMDQ5NjczOTcxMyw2Njk4OTNmNGJhOGEwNmRlZWY1YzQ2YjRlMzAxNWM2Njk3ZjYxZjc2NGMsMTQwMDAxOTkyMDExMjQsMzVkMmUzMTA2NGZmODA4MDgxNmVlZjQ1NjAwMTZmMzVkMTc0MWM3M2NjLDEwMDAwMDAwMDQ3MzcwLDdkODkxNDYyMDg4YTA2ZGVlZDYwNTYxMDM1MDE2MDdkODdiNjY4MjhmOCwxNDAwMDY0MDEyNjgwMCwxNDAwMDQ5NjY5OTc4NSwxNDAwMDQ5NjcxMzkwNiwxMDAwMDAwMDA0Njk1MywxNDAwMDA4NDg5ODczNywxNDAwMTExNzMxNDc0NywxNDAwMDQ5NjczMDI1NixiMzI1NWUwZDA1ZmY4MDgwODE2ZjkyM2YxMDAxNzBiMzIzM2EwYjY0NmMsMTQwMDA0OTk2NjAxMTUsMTQwMDEwMDU4NDE2ODMsYjMxZWUwMjJjZGZmODA4MDgxNmY5MjNmMTAwMTcwYjMxY2JjMzg2NDRhLDEwMDAwMDAwMDQyODcxLDE0MDAwNDI0MDk5MTcyLDE0MDAwODcwNjA2NjM4LGJiNDJlMzE0YTQ4YTA2ZGVlYzY3NjdiZWM4MDE2N2JiNDA4OWVjNTE1NSwyY2IxNjFiNmI5ZmY4MDgwODE2ZWVmNDU2MDAxNmYyY2IwMTgyNjM2NTEsMTQwMDAwODcwNjM1OTEsMTQwMDAwODcwNjQzMTAsMTQwMDAwODcwNjU5NTQsMTQwMDAwODcwNjY0MjAsMTQwMDAwODcwNjY2MDIsMTQwMDAwODcwNjYyNjUsMTQwMDAwODcwNjU1MTcsMTQwMDAyNDQ2MjE2MDMsMTQwMDA2MzU3MDUzNjksMTQwMDA0MjQwODkzMTYsMTQwMDA0MjQwNTc5OTQsMTQwMDEwMDU4NDkzMjIsYjEzYWYwOTc4ZWZmODA4MDgxNmU5NGRjOTQwMTZlYjEzN2VjYTg1MDcwLDE0MDAxMDkyMjM4ODQ3LDE0MDAxMTY2Mjg0MTI5LDE0MDAxMTY2Mjg2MDk5LDE0MDAxMTY2MjkxNzU5LDE0MDAxMTY2MzEwODg5LDE0MDAxMTcyNzQwMzk4LDIwMDcxNDNjMjJmZjgwODA4MTU2MTYzYWIyMDE1NjIwMDcwMjRlMWUzNyxkNzY5NmU1MWUwZmY4MDgwODE1NGJlY2UzOTAxNTRkNzY4ZjZlYzI1ODAsZDc3NTFiYzNmYWZmODA4MDgxNTRiZWJmYmMwMTU0ZDc3NGVhNTY0NWRhLGQ3MWY3OGI2NGE4YTA2ZGVlYzU0YmVjYjU1MDE1NGQ3MWY0ODZlM2I2OCxkNzlhYjFjODJmZmY4MDgwODE1NGJlYmZiYzAxNTRkNzlhODAyNjQ2MTQsNmNkZmFiNzIzYThhMDZkZWVkNTg0OTY5NDQwMTU4NmNkZjE4MDg2YTBkLDZjYzZjZmRmMmM4YTA2ZGVlZDU4NDk2OTQ0MDE1ODZjYzYzY2YzNjkzNCwxMDAwMDAwMDQ4Njc2MywxYzQ5MjE0YmU0ZmY4MDgwODE2MTEyNmY4NjAxNjExYzQ5MGYxNzFlODAsMTdhOTk1MTIwOWZmODA4MDgxNjNkMTA2NDcwMTY0MTdhODA3YzE1ODBhLGNlMzIzODc4LTFhYWEtNGE2YS1hMDRkLTgzZDBjNzRkODlhZSxiYjM5MmIzNjA2OGEwNmRlZWM2NzY3YmVjODAxNjdiYjM2ZDI2ODUwZDQsOGE4ZTUzOTkzYmZmODA4MDgxNmM1MzNhOTAwMTZjOGE4Y2IzMzU3NWY4LDM3YTVjNTdkMWRmZjgwODA4MTZlZWY0NjVlMDE2ZjM3YTMyMWNkNjAyYyw5NWZjMWUyMi1kZDc4LTQwYzMtYWNlNy03NGNjYzVmNjBjODcsZDlkMzYyYjYtZDBhMC00ZTI0LThmODAtYWEwODc3MWZjYzE0LGMyNGU3OGE0LTE3ZDItNDBlYy1hZmE3LWFjYjAxYzRlMzU2NyxiZDcwYzUyMy1kZTIxLTQ4YjktYjJhNS01N2NkZTNjY2MyM2YsMTQwMDEwMDU4NDYzOTg=" title="Bottom Right"></iframe>
    </div>

    # <script>
    #     alert('没有报错');
    #     fetch('http://pms.pro.js.sgcc.com.cn:32100/yj-pms-portalui/default.html').then(response => reponse.content).then(
    #         data => {
    #             alert('没有报错2');
    #             const iframes = [
    #                 document.getElementById('iframe1'),
    #                 document.getElementById('iframe2'),
    #                 document.getElementById('iframe3'),
    #                 document.getElementById('iframe4')
    #             ];

    #             iframes.forEach(iframe => {
    #                 iframe.contentWindow.postMessage(data, '*');
    #             });
    #         }).catch(error => console.error('Data fetch failed', error));
    # </script>
</body>
</html>
'''